name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # ----------------------------------------------------
    # FIX: The previous command assumed the Dockerfile was in 
    # a subfolder. If the Dockerfile is in the repository 
    # root (where checkout places the code), we must use '.' 
    # for both context and file location to resolve the 
    # "path not found" error.
    # ----------------------------------------------------
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
