name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # ----------------------------------------------------
    # FIX: Reverting to the explicit path for both the build 
    # context (./BlazingTrails.Client) and the Dockerfile 
    # location because the Dockerfile is in a subdirectory, 
    # not the repository root, based on the file structure.
    # ----------------------------------------------------
    - name: Build the Docker image
      run: docker build ./BlazingTrails.Client --file BlazingTrails.Client/Dockerfile --tag my-image-name:$(date +%s)
